webview: bp: Declare com.android.extensions.xr as optional library
```
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: []
	- optional libraries in build system: [androidx.window.extensions]
	    and missing ones in build system: []
	                 vs. in the manifest: [androidx.window.extensions, com.android.extensions.xr]
	- tags in the manifest (external/chromium-webview/prebuilt/arm64/webview.apk):
		uses-library-not-required:'androidx.window.extensions'		uses-library-not-required:'com.android.extensions.xr'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- for details, see build/make/Changes.md and https://source.android.com/devices/tech/dalvik/art-class-loader-context
```

Note: mk changes not necessary as `LOCAL_ENFORCE_USES_LIBRARIES := false` is set,

Change-Id: I22a43fdf4eed47b2a2fc2e0c385f7f2eec7de418